import searchSong from "../spotify/seachSong.js";
import getAccessToken from "../spotify/accessToken.js";

describe('SearchSongSuccess', () => {
  it('should return search results when the request is successful', async () => {
    const clientId = process.env.SPOTIFY_CLIENT_ID;
    const clientSecret = process.env.SPOTIFY_CLIENT_SECRET;
    const refreshToken = process.env.SPOTIFY_REFRESH_TOKEN;
    const { access_token } = await getAccessToken(clientId, clientSecret, refreshToken);
    const mockResponseData = {
      "tracks": {
        "href": "https://api.spotify.com/v1/search?query=remastered+%2B+track%3A+%2B+Miles+Davis+%2B+artist%3A+Doxy&type=track&locale=*&offset=0&limit=1",
        "items": [
          {
            "album": {
              "album_type": "album",
              "artists": [
                {
                  "external_urls": {
                    "spotify": "https://open.spotify.com/artist/0kbYTNQb4Pb1rPbbaF0pT4"
                  },
                  "href": "https://api.spotify.com/v1/artists/0kbYTNQb4Pb1rPbbaF0pT4",
                  "id": "0kbYTNQb4Pb1rPbbaF0pT4",
                  "name": "Miles Davis",
                  "type": "artist",
                  "uri": "spotify:artist:0kbYTNQb4Pb1rPbbaF0pT4"
                }
              ],
              "available_markets": [
                "AR",
                "AU",
                "AT",
                "BE",
                "BO",
                "BR",
                "BG",
                "CA",
                "CL",
                "CO",
                "CR",
                "CY",
                "CZ",
                "DK",
                "DO",
                "DE",
                "EC",
                "EE",
                "SV",
                "FI",
                "FR",
                "GR",
                "GT",
                "HN",
                "HK",
                "HU",
                "IS",
                "IE",
                "IT",
                "LV",
                "LT",
                "LU",
                "MY",
                "MT",
                "MX",
                "NL",
                "NZ",
                "NI",
                "NO",
                "PA",
                "PY",
                "PE",
                "PH",
                "PL",
                "PT",
                "SG",
                "SK",
                "ES",
                "SE",
                "CH",
                "TW",
                "TR",
                "UY",
                "US",
                "GB",
                "AD",
                "LI",
                "MC",
                "ID",
                "JP",
                "TH",
                "VN",
                "RO",
                "IL",
                "ZA",
                "SA",
                "AE",
                "BH",
                "QA",
                "OM",
                "KW",
                "EG",
                "MA",
                "DZ",
                "TN",
                "LB",
                "JO",
                "PS",
                "IN",
                "BY",
                "KZ",
                "MD",
                "UA",
                "AL",
                "BA",
                "HR",
                "ME",
                "MK",
                "RS",
                "SI",
                "KR",
                "BD",
                "PK",
                "LK",
                "GH",
                "KE",
                "NG",
                "TZ",
                "UG",
                "AG",
                "AM",
                "BS",
                "BB",
                "BZ",
                "BT",
                "BW",
                "BF",
                "CV",
                "CW",
                "DM",
                "FJ",
                "GM",
                "GE",
                "GD",
                "GW",
                "GY",
                "HT",
                "JM",
                "KI",
                "LS",
                "LR",
                "MW",
                "MV",
                "ML",
                "MH",
                "FM",
                "NA",
                "NR",
                "NE",
                "PW",
                "PG",
                "WS",
                "SM",
                "ST",
                "SN",
                "SC",
                "SL",
                "SB",
                "KN",
                "LC",
                "VC",
                "SR",
                "TL",
                "TO",
                "TT",
                "TV",
                "VU",
                "AZ",
                "BN",
                "BI",
                "KH",
                "CM",
                "TD",
                "KM",
                "GQ",
                "SZ",
                "GA",
                "GN",
                "KG",
                "LA",
                "MO",
                "MR",
                "MN",
                "NP",
                "RW",
                "TG",
                "UZ",
                "ZW",
                "BJ",
                "MG",
                "MU",
                "MZ",
                "AO",
                "CI",
                "DJ",
                "ZM",
                "CD",
                "CG",
                "IQ",
                "LY",
                "TJ",
                "VE",
                "ET",
                "XK"
              ],
              "external_urls": {
                "spotify": "https://open.spotify.com/album/3rs2Wq1755vGmXxIioU7Xo"
              },
              "href": "https://api.spotify.com/v1/albums/3rs2Wq1755vGmXxIioU7Xo",
              "id": "3rs2Wq1755vGmXxIioU7Xo",
              "images": [
                {
                  "height": 640,
                  "url": "https://i.scdn.co/image/ab67616d0000b27342a04303e6eb1100df3ea036",
                  "width": 640
                },
                {
                  "height": 300,
                  "url": "https://i.scdn.co/image/ab67616d00001e0242a04303e6eb1100df3ea036",
                  "width": 300
                },
                {
                  "height": 64,
                  "url": "https://i.scdn.co/image/ab67616d0000485142a04303e6eb1100df3ea036",
                  "width": 64
                }
              ],
              "name": "Bags' Groove (Rudy Van Gelder Remaster)",
              "release_date": "1957-01-01",
              "release_date_precision": "day",
              "total_tracks": 7,
              "type": "album",
              "uri": "spotify:album:3rs2Wq1755vGmXxIioU7Xo"
            },
            "artists": [
              {
                "external_urls": {
                  "spotify": "https://open.spotify.com/artist/0kbYTNQb4Pb1rPbbaF0pT4"
                },
                "href": "https://api.spotify.com/v1/artists/0kbYTNQb4Pb1rPbbaF0pT4",
                "id": "0kbYTNQb4Pb1rPbbaF0pT4",
                "name": "Miles Davis",
                "type": "artist",
                "uri": "spotify:artist:0kbYTNQb4Pb1rPbbaF0pT4"
              },
              {
                "external_urls": {
                  "spotify": "https://open.spotify.com/artist/1VEzN9lxvG6KPR3QQGsebR"
                },
                "href": "https://api.spotify.com/v1/artists/1VEzN9lxvG6KPR3QQGsebR",
                "id": "1VEzN9lxvG6KPR3QQGsebR",
                "name": "Sonny Rollins",
                "type": "artist",
                "uri": "spotify:artist:1VEzN9lxvG6KPR3QQGsebR"
              },
              {
                "external_urls": {
                  "spotify": "https://open.spotify.com/artist/5ZATfKurLqflrBhv2FLht5"
                },
                "href": "https://api.spotify.com/v1/artists/5ZATfKurLqflrBhv2FLht5",
                "id": "5ZATfKurLqflrBhv2FLht5",
                "name": "Horace Silver",
                "type": "artist",
                "uri": "spotify:artist:5ZATfKurLqflrBhv2FLht5"
              },
              {
                "external_urls": {
                  "spotify": "https://open.spotify.com/artist/7xwlN7fhoOwNgDmRTwYZOa"
                },
                "href": "https://api.spotify.com/v1/artists/7xwlN7fhoOwNgDmRTwYZOa",
                "id": "7xwlN7fhoOwNgDmRTwYZOa",
                "name": "Kenny Clarke",
                "type": "artist",
                "uri": "spotify:artist:7xwlN7fhoOwNgDmRTwYZOa"
              },
              {
                "external_urls": {
                  "spotify": "https://open.spotify.com/artist/0vKbTTNdtagd8xiERj6Szb"
                },
                "href": "https://api.spotify.com/v1/artists/0vKbTTNdtagd8xiERj6Szb",
                "id": "0vKbTTNdtagd8xiERj6Szb",
                "name": "Percy Heath",
                "type": "artist",
                "uri": "spotify:artist:0vKbTTNdtagd8xiERj6Szb"
              }
            ],
            "available_markets": [
              "AR",
              "AU",
              "AT",
              "BE",
              "BO",
              "BR",
              "BG",
              "CA",
              "CL",
              "CO",
              "CR",
              "CY",
              "CZ",
              "DK",
              "DO",
              "DE",
              "EC",
              "EE",
              "SV",
              "FI",
              "FR",
              "GR",
              "GT",
              "HN",
              "HK",
              "HU",
              "IS",
              "IE",
              "IT",
              "LV",
              "LT",
              "LU",
              "MY",
              "MT",
              "MX",
              "NL",
              "NZ",
              "NI",
              "NO",
              "PA",
              "PY",
              "PE",
              "PH",
              "PL",
              "PT",
              "SG",
              "SK",
              "ES",
              "SE",
              "CH",
              "TW",
              "TR",
              "UY",
              "US",
              "GB",
              "AD",
              "LI",
              "MC",
              "ID",
              "JP",
              "TH",
              "VN",
              "RO",
              "IL",
              "ZA",
              "SA",
              "AE",
              "BH",
              "QA",
              "OM",
              "KW",
              "EG",
              "MA",
              "DZ",
              "TN",
              "LB",
              "JO",
              "PS",
              "IN",
              "BY",
              "KZ",
              "MD",
              "UA",
              "AL",
              "BA",
              "HR",
              "ME",
              "MK",
              "RS",
              "SI",
              "KR",
              "BD",
              "PK",
              "LK",
              "GH",
              "KE",
              "NG",
              "TZ",
              "UG",
              "AG",
              "AM",
              "BS",
              "BB",
              "BZ",
              "BT",
              "BW",
              "BF",
              "CV",
              "CW",
              "DM",
              "FJ",
              "GM",
              "GE",
              "GD",
              "GW",
              "GY",
              "HT",
              "JM",
              "KI",
              "LS",
              "LR",
              "MW",
              "MV",
              "ML",
              "MH",
              "FM",
              "NA",
              "NR",
              "NE",
              "PW",
              "PG",
              "WS",
              "SM",
              "ST",
              "SN",
              "SC",
              "SL",
              "SB",
              "KN",
              "LC",
              "VC",
              "SR",
              "TL",
              "TO",
              "TT",
              "TV",
              "VU",
              "AZ",
              "BN",
              "BI",
              "KH",
              "CM",
              "TD",
              "KM",
              "GQ",
              "SZ",
              "GA",
              "GN",
              "KG",
              "LA",
              "MO",
              "MR",
              "MN",
              "NP",
              "RW",
              "TG",
              "UZ",
              "ZW",
              "BJ",
              "MG",
              "MU",
              "MZ",
              "AO",
              "CI",
              "DJ",
              "ZM",
              "CD",
              "CG",
              "IQ",
              "LY",
              "TJ",
              "VE",
              "ET",
              "XK"
            ],
            "disc_number": 1,
            "duration_ms": 293640,
            "explicit": false,
            "external_ids": {
              "isrc": "USC4R0720006"
            },
            "external_urls": {
              "spotify": "https://open.spotify.com/track/3vZIYc2V9Ql80jWI2ZApEC"
            },
            "href": "https://api.spotify.com/v1/tracks/3vZIYc2V9Ql80jWI2ZApEC",
            "id": "3vZIYc2V9Ql80jWI2ZApEC",
            "is_local": false,
            "name": "Doxy - RVG Remaster",
            "popularity": 35,
            "preview_url": null,
            "track_number": 6,
            "type": "track",
            "uri": "spotify:track:3vZIYc2V9Ql80jWI2ZApEC"
          }
        ],
        "limit": 1,
        "next": "https://api.spotify.com/v1/search?query=remastered+%2B+track%3A+%2B+Miles+Davis+%2B+artist%3A+Doxy&type=track&locale=*&offset=1&limit=1",
        "offset": 0,
        "previous": null,
        "total": 39
      }
    }
    const result = await searchSong(access_token, "Miles Davis", "Doxy", "track", "1", "0" );
    expect(result).toEqual(mockResponseData);
  });
});